sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mypassword
      - MSSQL_PID=Developer
    user: root
    ports:
      - 1433:1433
    volumes:
      - /docker/mssql:/var/opt/mssql
    restart: always