  obsidian:
    image: lscr.io/linuxserver/obsidian:1.8.4
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /obsidian/config:/config
    ports:
      - 8081:3000
      - 8082:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped
