jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /jellyfin/config:/config
      - /jellyfin/cache:/cache
      - type: bind
        source: /srv/Movies
        target: /movies
      - type: bind
        source: /srv/Series
        target: /tv_series
      - type: bind
        source: /srv/Music
        target: /music
    restart: 'unless-stopped'